
version: 2

sources:
    - name: staging
      #For bigquery:
      database: de-z-camp

      # For postgres:
      #database: production

      schema: de_ag

      # loaded_at_field: record_loaded_at
      tables:
        - name: external_commodity_data
        - name: external_commodity_ref
        - name: external_country_ref
        - name: external_region_ref
        - name: external_unit_ref
         # freshness:
           # error_after: {count: 6, period: hour}

# https://apps.fas.usda.gov/opendataweb/home
models:
    - name: stg_commodity_data
      description: >
        Holds records of amounts of a commodity exported from the U.S. by Market Year
      columns:
          - name: commodityCode
            description: Code for commodity being exported. Codes listed in commodity_ref. Composite primary key along with countryCode and weekEndingDate.
            tests:
              - not_null:
                    severity: warn
          - name: commodityName 
            description: Commodity's name.
          - name: countryCode 
            description: Code for country commodity is being exported to. Codes listed in country_ref. Composite primary key along with commodityCode and weekEndingDate.
          - name: countryName 
            description: Country's name.
          - name: regionId
            description: Unique code per region.
          - name: regionName 
            description: Region's name.
          - name: weeklyExports 
            description: Sum of total exports in week (units given by unitID).
          - name: accumulatedExports 
            description: Sum of weeklyExports for market year by the week of this record.
          - name: outstanding_sales 
            description: Count of export sales currently outstanding (units given by unitID).
          - name: grossNewSales 
            description: Export total for week of this record (units given by unitID).
          - name:  currentMYNetSales
            description: Net sales total for market year by week of this record (units given by unitID).
          - name:  currentMYTotalCommitment
            description: Sales total including sales commitments for market year by week of this record.
          - name:  nextMYOutstandingSales
            description: Outstanding sales total for next market year by week of this record (units given by unitID).
          - name:  nextMYNetSales
            description: Net sales total for next market year by week of this record (units given by unitID).
          - name:  unitId
            description: Unit for amounts. Codes listed in unit_ref.
          - name: unitName
            description: Unit's name.
          - name: weekendingDate
            description: Week of record. Composite primary key along with countryCode and commodityCode.







